package com.crady.pojo;

import lombok.Data;

import java.util.Date;

@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.balance
     *
     * @mbg.generated
     */
    private Integer balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.crt_time
     *
     * @mbg.generated
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.upd_time
     *
     * @mbg.generated
     */
    private Date updTime;

}