package com.crady.pojo;

import lombok.Data;

import java.util.Date;
@Data
public class MoneyDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_detail.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_detail.type
     *
     * @mbg.generated
     */
    private Boolean type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_detail.amount
     *
     * @mbg.generated
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money_detail.crt_time
     *
     * @mbg.generated
     */
    private Date crtTime;

}