package com.crady.mapper;

import com.crady.pojo.MoneyDetail;
import org.springframework.stereotype.Repository;

@Repository
public interface MoneyDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_detail
     *
     * @mbg.generated
     */
    int insert(MoneyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_detail
     *
     * @mbg.generated
     */
    int insertSelective(MoneyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_detail
     *
     * @mbg.generated
     */
    MoneyDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MoneyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MoneyDetail record);
}